// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_Vehiculo_ID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_Vehiculo_ID));
        
        string IMigrationMetadata.Id
        {
            get { return "201704111226031_update_Vehiculo_ID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
